### ISSUE TITLE
permission这个表的前端路由跟后端路由是怎么用的？

### ISSUE THREAD

**Issue by leeseean** [zze326/zze-admin-go#1]
这个菜单管理，应该是后端根据角色生成菜单，然后前端拿到后展示吧。
按钮这个的权限你是怎么弄的？

**Comment by zze326** [comment]
1. 后端根据角色生成菜单：是的，后端返回原始列表，前端组装成菜单树；
2. 按钮权限：每个菜单权限下的功能权限对应着按钮权限，每个按钮权限会渲染到菜单对应的前端路由对象的 meta.auths 中，前端具体实现参考[PureAdmin RBAC 文档](https://yiming_chang.gitee.io/pure-admin-doc/pages/RBAC/#%E6%8C%89%E9%92%AE%E3%80%81%E7%BB%84%E4%BB%B6%E3%80%81%E7%B1%BB%E6%96%B9%E6%B3%95%E6%9D%83%E9%99%90)；
3. 后端路由：即后端接口权限，通常一个页面可能多个后端接口，这些后端接口保存到了页面下的功能权限中，后端使用 casbin  通过获取用户角色关联的权限下的功能权限包含的后端接口来进行后端接口访问的授权；

**Comment by leeseean** [comment]
> 1. 后端根据角色生成菜单：是的，后端返回原始列表，前端组装成菜单树；
> 2. 按钮权限：每个菜单权限下的功能权限对应着按钮权限，每个按钮权限会渲染到菜单对应的前端路由对象的 meta.auths 中，前端具体实现参考[PureAdmin RBAC 文档](https://yiming_chang.gitee.io/pure-admin-doc/pages/RBAC/#%E6%8C%89%E9%92%AE%E3%80%81%E7%BB%84%E4%BB%B6%E3%80%81%E7%B1%BB%E6%96%B9%E6%B3%95%E6%9D%83%E9%99%90)；
> 3. 后端路由：即后端接口权限，通常一个页面可能多个后端接口，这些后端接口保存到了页面下的功能权限中，后端使用 casbin  通过获取用户角色关联的权限下的功能权限包含的后端接口来进行后端接口访问的授权；

我觉得这个按钮权限应该跟角色关联，而不是跟菜单关联。因为同一个菜单可能多个角色都可以访问，但是有的角色不能操作这个菜单的按钮

**Comment by zze326** [comment]
**你还有这个问题就说明你没看或者没看懂上面发的那个 PureAdmin RBAC 文档。**
你这个觉得本身就有问题，**因为角色是关联权限，又不是关联菜单（页面）**，按钮（功能）权限和页面（菜单）权限在数据层面是平级的，只是在前端路由的角度上做了一个逻辑权限树，多个角色本来就可以分别选择不同的按钮权限，比如管理员角色有新增用户权限：
<img width="278" alt="image" src="https://github.com/zze326/zze-admin-go/assets/49554487/a14d20d0-2290-48c0-afed-76540691137b">
测试角色没有新增用户权限：
<img width="261" alt="image" src="https://github.com/zze326/zze-admin-go/assets/49554487/adb0038d-889e-4998-b25c-0485fff0e393">
对应到页面的反馈就是管理员看得到新增按钮，测试角色看不到测试按钮。
不同角色最终的路由对象数据 demo 就是：
管理员角色：
```json
 { "name": "user-manage", "auths": ["read", "insert"] }
```
测试角色：
```json
{ "name": "user-manage", "auths": ["read"] } 
```


### 看源码、看文档、预览测效果。

**Comment by apple1563** [comment]
> **你还有这个问题就说明你没看或者没看懂上面发的那个 PureAdmin RBAC 文档。** 你这个觉得本身就有问题，**因为角色是关联权限，又不是关联菜单（页面）**，按钮（功能）权限和页面（菜单）权限在数据层面是平级的，只是在前端路由的角度上做了一个逻辑权限树，多个角色本来就可以分别选择不同的按钮权限，比如管理员角色有新增用户权限： <img alt="image" width="278" src="https://user-images.githubusercontent.com/49554487/271782353-a14d20d0-2290-48c0-afed-76540691137b.png"> 测试角色没有新增用户权限： <img alt="image" width="261" src="https://user-images.githubusercontent.com/49554487/271782380-adb0038d-889e-4998-b25c-0485fff0e393.png"> 对应到页面的反馈就是管理员看得到新增按钮，测试角色看不到测试按钮。 不同角色最终的路由对象数据 demo 就是： 管理员角色：
> 
> ```json
>  { "name": "user-manage", "auths": ["read", "insert"] }
> ```
> 
> 测试角色：
> 
> ```json
> { "name": "user-manage", "auths": ["read"] } 
> ```
> 
> ### 看源码、看文档、预览测效果。

看了下讨论。我觉得这个按钮可以不放在meta.auths里，我们可以用一个接口返回所有这个角色的权限按钮数组，然后前端vue写一个指令，判断这个按钮有没有包含在后端返回的按钮列表里，没有则不显示

**Comment by zze326** [comment]
> > **你还有这个问题就说明你没看或者没看懂上面发的那个 PureAdmin RBAC 文档。** 你这个觉得本身就有问题，**因为角色是关联权限，又不是关联菜单（页面）**，按钮（功能）权限和页面（菜单）权限在数据层面是平级的，只是在前端路由的角度上做了一个逻辑权限树，多个角色本来就可以分别选择不同的按钮权限，比如管理员角色有新增用户权限： <img alt="image" width="278" src="https://user-images.githubusercontent.com/49554487/271782353-a14d20d0-2290-48c0-afed-76540691137b.png"> 测试角色没有新增用户权限： <img alt="image" width="261" src="https://user-images.githubusercontent.com/49554487/271782380-adb0038d-889e-4998-b25c-0485fff0e393.png"> 对应到页面的反馈就是管理员看得到新增按钮，测试角色看不到测试按钮。 不同角色最终的路由对象数据 demo 就是： 管理员角色：
> > ```json
> >  { "name": "user-manage", "auths": ["read", "insert"] }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 测试角色：
> > ```json
> > { "name": "user-manage", "auths": ["read"] } 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 看源码、看文档、预览测效果。
> 
> 看了下讨论。我觉得这个按钮可以不放在meta.auths里，我们可以用一个接口返回所有这个角色的权限按钮数组，然后前端vue写一个指令，判断这个按钮有没有包含在后端返回的按钮列表里，没有则不显示

1. 这里我是直接对接 Pure Admin 的，它本身是这样设计的，我就没改这块逻辑；
2. 我以前的确有这么做过 -【返回所有这个角色的权限按钮数组】，但是实际开发中会发现 Pure Admin 更合理。
  - 因为按钮一定是对应到某个页面（路由）的，如果笼统的返回一个数组，当你要判断是否拥有某个按钮权限时，你每次**去循环对比权限是否存在**这个逻辑是会多循环很多次数的（抛开字典不谈），比如一个系统有 1000 个按钮权限，无论判断哪个页面的哪个按钮权限都可能要遍历 1000 次去比对；
  - 另外一点，如果所有按钮权限都在一个数组，你就要考虑到按钮标识的唯一性，比如有权限读和用户读两个权限，你就必须人为的去将它设置成类似 permiss-read 和 user-read 这种形式，而 Pure Admin 这种页面维度的形式是可以都使用 read，我认为更加直观方便了；
