### ISSUE TITLE
接口如何限制传参？

### ISSUE THREAD

**Issue by apple1563** [zze326/zze-admin-go#3]
一个接口查询用户信息  ，如  /api/user?userId=xxx
有两个角色，一个是管理员，一个是代理，他们都有这个接口的权限。
管理员可以查询所有用户，代理只能查询他的下级。
如何防止代理传参userId不属于他自己下属的userId查询其他人信息？

**Comment by zze326** [comment]
这种已经属于基础系统功能外的业务逻辑了，只能额外加拦截器或者在 /api/user 对应的 handler 里手动写逻辑处理

**Comment by apple1563** [comment]
> 这种已经属于基础系统功能外的业务逻辑了，只能额外加拦截器或者在 /api/user 对应的 handler 里手动写逻辑处理

这样搞的话，100个接口，就要加100个判断。太麻烦了吧

**Comment by zze326** [comment]
> > 这种已经属于基础系统功能外的业务逻辑了，只能额外加拦截器或者在 /api/user 对应的 handler 里手动写逻辑处理
> 
> 这样搞的话，100个接口，就要加100个判断。太麻烦了吧

不对吧，如果你的 100 个接口都是针对要求【只能查询下级】来说，一个拦截器里写一次这个逻辑就够了，在 java 里就类似是给 handler 加 aop 注解了

**Comment by apple1563** [comment]
> > > 这种已经属于基础系统功能外的业务逻辑了，只能额外加拦截器或者在 /api/user 对应的 handler 里手动写逻辑处理
> > 
> > 
> > 这样搞的话，100个接口，就要加100个判断。太麻烦了吧
> 
> 不对吧，如果你的 100 个接口都是针对要求【只能查询下级】来说，一个拦截器里写一次这个逻辑就够了，在 java 里就类似是给 handler 加 aop 注解了

找到了代替 casbin的解决方案，api gateway。可以做到参数级的限制
