### ISSUE TITLE
删除用户的问题

### ISSUE THREAD

**Issue by apple1563** [zze326/zze-admin-go#4]
删除一个用户，如果这个用户关联到上下级，是否会影响上下级树。
比如一个用户甲有上级A，有下级CDEFGHJK等。
当删除用户甲后，他的下级CDEFGHJK的上级就找不到了。这个怎么处理？

**Comment by zze326** [comment]
在本系统中所有用户是平级的，不存在你说的用户上下级的情况。
部门和权限有树的概念，但是这个树只是用于前端展示，以部门为例，如果删除一个中间部门，那么被删除部门的下级权限在前端将会默认展示为顶级部门，如果你有其它的逻辑，建议在删除部门接口处理，比如你要将删除部门的下级放到删除部门父级的下级。

**Comment by apple1563** [comment]
> 在本系统中所有用户是平级的，不存在你说的用户上下级的情况。 部门和权限有树的概念，但是这个树只是用于前端展示，以部门为例，如果删除一个中间部门，那么被删除部门的下级权限在前端将会默认展示为顶级部门，如果你有其它的逻辑，建议在删除部门接口处理，比如你要将删除部门的下级放到删除部门父级的下级。

我改的是有上下级的，业务更深
